name: Test TP

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pytest==6.2.5
        pip install pytest-mock==3.6.1
        pip install pandas==1.1.5
        pip install requests==2.26.0
        pip install SQLAlchemy==1.3.24
    - name: Test with pytest
      run: |
        pytest dags
